### ISSUE TITLE
Add support for parsing more than one package

### ISSUE THREAD

**Issue by yash-nisar** [spdx/tools-python#79]
The current implementation only supports parsing a single package in the SPDX document. There can be one or more packages as mentioned [here](https://spdx.org/sites/cpstandard/files/pages/files/spdxversion2.1.pdf#page=18). We should add support for parsing more than one package.

**Comment by ro22110** [comment]
Not sure this issue has been resolved or I am doing something wrong, I just couldn't get it to work with multiple packages, I'am always getting the error:

spdx.parsers.builderexceptions.OrderError: File::SPDXID

**Comment by yogini-ghode** [comment]
@licquia , we are still facing same issue with multiple packages.
"spdx.parsers.builderexceptions.OrderError: File::SPDXID" 
Can you please let us know how we can get over it?
