### ISSUE TITLE
Fix type: 'impor' -> 'import'

### ISSUE THREAD

**Issue by kaiz123** [spdx/tools-python#83]
Fix typo in document.py

**Comment by kaiz123** [comment]
I have fixed this issue. Can someone approve it. Thanks

**Comment by rtgdk** [comment]
@kaiz123  Don't forget to the tag this issue in your PR. Easier to maintain open issues.

**Comment by Purvanshsingh** [comment]
I think the issue is not solved yet,
As I am a Newcomer can I work on this issue?

**Comment by anshuldutt21** [comment]
Can anyone please review my pull request #127

**Comment by meretp** [comment]
@nicoweidner issue can be closed.
